version: 2

models:
  - name: dim_listings_clean
    description: Cleansed table which contains Airbnb listings.
    columns:
      
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique
          - not_null
        
      - name: host_id
        description: The hosts's id. References the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_clean')
              field: host_id

      - name: room_type
        description: Type of the apartment / room
        tests:
          - accepted_values:
              values: ['Entire home/apt', 
                        'Private room', 
                        'Shared room', 
                        'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listing_clean__minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_hosts_clean
    description: Cleansed table which contains Airbnb hosts.
    columns:
      
      - name: host_id
        description: Primary key for the hosts
        tests:
          - unique
          - not_null
          
      - name: host_name
        description: Name of the host
        tests:
          - not_null

      - name: is_superhost
        description: Indicator if a host is a superhost 
        tests:
          - accepted_values:
              values: ['f', 't']

  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source ('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .95
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn


  - name: fct_reviews
    columns:
      - name: listing_id
        tests:
          - relationships:
              to: ref('dim_listings_cleansed')
              field: listing_id

      - name: reviewer_name
        tests:
          - not_null
      
      - name: review_sentiment
        tests:
          - accepted_values:
              values: ['positive', 'neutral', 'negative']


    