version: 2

models:
  - name: dim_listings_clean
    description: Cleansed table which contains Airbnb listings.
    columns:
      
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique
          - not_null
        
      - name: host_id
        description: The hosts's id. References the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_clean')
              field: host_id

      - name: room_type
        description: Type of the apartment / room
        tests:
          - accepted_values:
              values: ['Entire home/apt', 
                        'Private room', 
                        'Shared room', 
                        'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listing_clean__minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_hosts_clean
    description: Cleansed table which contains Airbnb hosts.
    columns:
      
      - name: host_id
        description: Primary key for the hosts
        tests:
          - unique
          - not_null
          
      - name: host_name
        description: Name of the host
        tests:
          - not_null

      - name: is_superhost
        description: Indicator if a host is a superhost 
        tests:
          - accepted_values:
              values: ['f', 't']

    